-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Nov 23, 2019 at 12:45 PM
-- Server version: 10.3.13-MariaDB-log
-- PHP Version: 7.2.22

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `vstalt_vsta`
--

-- --------------------------------------------------------

--
-- Table structure for table `events`
--

CREATE TABLE `events` (
  `id` int(10) UNSIGNED NOT NULL,
  `ename` varchar(191) COLLATE utf8_unicode_ci NOT NULL,
  `edesc` varchar(1500) COLLATE utf8_unicode_ci NOT NULL,
  `egroup1` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL,
  `egroup2` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL,
  `egroup3` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL,
  `egroup4` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL,
  `egroup5` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL,
  `egroup6` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL,
  `egroup7` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL,
  `egroup8` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `edate` varchar(191) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `events`
--

INSERT INTO `events` (`id`, `ename`, `edesc`, `egroup1`, `egroup2`, `egroup3`, `egroup4`, `egroup5`, `egroup6`, `egroup7`, `egroup8`, `created_at`, `updated_at`, `edate`) VALUES
(6, 'Žemaitijos regiono asmeninės vaikų pirmenybės - Mergaitės 2002-2006', '<p><strong>Žemaitijos regiono asmeninės vaikų pirmenybės</strong></p>\r\n\r\n<p><strong>Mergaitės 2002-2006</strong></p>\r\n\r\n<p><strong>TIKSLAS IR UŽDAVINIAI</strong> 1. Populiarinti stalo tenisą Žemaitijos regionų gyventojų tarpe; 2. Skatinti fizinį vaikų aktyvumą; 3. Kelti stalo tenisininkų sportinio meistri&scaron;kumo lygį; 4. Plėtoti draugi&scaron;kus ry&scaron;ius tarp stalo teniso klubų.</p>', 'Mergaitės 2002-2006', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2019-03-12 09:29:54', '2019-03-12 09:29:54', '2019-03-31'),
(7, 'Žemaitijos regiono asmeninės vaikų pirmenybės - Mergaitės 2007 ir jaunesnės', '<p><strong>Žemaitijos regiono asmeninės vaikų pirmenybės &nbsp;</strong></p>\r\n\r\n<p><strong>Mergaitės 2007 ir jaunesnės</strong></p>\r\n\r\n<p><strong>TIKSLAS IR UŽDAVINIAI</strong> 1. Populiarinti stalo tenisą Žemaitijos regionų gyventojų tarpe; 2. Skatinti fizinį vaikų aktyvumą; 3. Kelti stalo tenisininkų sportinio meistri&scaron;kumo lygį; 4. Plėtoti draugi&scaron;kus ry&scaron;ius tarp stalo teniso klubų.</p>', 'Mergaitės 2007 ir jaunesnės', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2019-03-12 09:30:36', '2019-03-12 09:30:36', '2019-03-31'),
(8, 'Žemaitijos regiono asmeninės vaikų pirmenybės - Berniukai 2003-2006', '<p><strong>Žemaitijos regiono asmeninės vaikų pirmenybės </strong></p>\r\n\r\n<p><strong>Berniukai 2003-2006</strong></p>\r\n\r\n<p><strong>TIKSLAS IR UŽDAVINIAI</strong> 1. Populiarinti stalo tenisą Žemaitijos regionų gyventojų tarpe; 2. Skatinti fizinį vaikų aktyvumą; 3. Kelti stalo tenisininkų sportinio meistri&scaron;kumo lygį; 4. Plėtoti draugi&scaron;kus ry&scaron;ius tarp stalo teniso klubų.</p>', 'Berniukai 2003-2006', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2019-03-12 09:31:21', '2019-03-12 09:31:21', '2019-03-31'),
(9, 'Žemaitijos regiono asmeninės vaikų pirmenybės - Berniukai 2007 ir jaunesni', '<p><strong>&nbsp;Žemaitijos regiono asmeninės vaikų pirmenybės </strong></p>\r\n\r\n<p><strong>Berniukai 2007 ir jaunesni</strong></p>\r\n\r\n<p><strong>TIKSLAS IR UŽDAVINIAI</strong> 1. Populiarinti stalo tenisą Žemaitijos regionų gyventojų tarpe; 2. Skatinti fizinį vaikų aktyvumą; 3. Kelti stalo tenisininkų sportinio meistri&scaron;kumo lygį; 4. Plėtoti draugi&scaron;kus ry&scaron;ius tarp stalo teniso klubų.</p>', 'Berniukai 2007 ir jaunesni', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2019-03-12 09:31:58', '2019-03-12 09:31:58', '2019-03-31'),
(10, 'Stalo teniso - VILTIES TURNYRAS', '<p><!-- wp:paragraph -->Kviečiame visus norinčius dalyvauti <strong>Stalo teniso - VILTIES TURNYRE</strong><br />\r\nTai <strong>Asmeninis turnyras</strong> - kurio metu visos surinktos lė&scaron;os bus skirtos Benedikto vaikų centrui paremti.</p>\r\n\r\n<p><!-- /wp:paragraph --><!-- wp:paragraph --></p>\r\n\r\n<p><strong>Varžybų data - 05/11 d. | Pradžia 11:00 val.</strong> | Startinis mokestis - 10 eur.</p>\r\n\r\n<p><!-- /wp:paragraph --><!-- wp:paragraph --></p>\r\n\r\n<p><strong>Varžybos vyks </strong>- Vakarų stalo teniso akademijoje | Taikos pr. 70, Klaipėda</p>\r\n\r\n<p><!-- /wp:paragraph --></p>', 'Bendra', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2019-04-30 15:28:41', '2019-04-30 15:28:41', '2019-05-11'),
(11, 'Mergaitės 2004-2006 - Klaipėda Open 2019', '<p>TURNYRO TIKSLAS<br />\r\n&bull; Populiarinti stalo teniso sporto &scaron;aką;<br />\r\n&bull; plėtoti draugi&scaron;kus ry&scaron;ius ne tik Lietuvoje, bet ir su užsienio sportininkais;<br />\r\n&bull; kelti žaidėjų meistri&scaron;kumą.<br />\r\nLAIKAS, VIETA, DALYVIAI<br />\r\nVaržybos vyks 2018 rugpjūčio 16-18 dienomis Klaipėdoje, adresu Taikos pr. 70;<br />\r\n&bull; rugpjūčio 16 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis vaikai:<br />\r\nmini jaunučiai (-tės) 2007 gim. ir jaunesni;<br />\r\njaunučiai (-tės) 2004 &ndash; 2006 gim.<br />\r\nStartinis mokestis 7 eur.<br />\r\n&bull; rugpjūčio 17 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis visi norintys vyrai ir moterys<br />\r\n(moterys ir vyrai žais atskirai);<br />\r\nStartinis mokestis 15 eur.<br />\r\n&bull; rugpjūčio 18 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis vyrai nuo 50 m. ir moterys nuo 40<br />\r\nm. (moterys ir vyrai žais atskirai);<br />\r\nStartinis mokestis 10 eur.</p>', 'Mergaitės 2004-2006', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2019-07-23 13:51:33', '2019-07-23 13:51:33', '2019-08-16'),
(12, 'Mergaitės 2007 ir jaunesnės - Klaipėda Open 2019', '<p>TURNYRO TIKSLAS<br />\r\n&bull; Populiarinti stalo teniso sporto &scaron;aką;<br />\r\n&bull; plėtoti draugi&scaron;kus ry&scaron;ius ne tik Lietuvoje, bet ir su užsienio sportininkais;<br />\r\n&bull; kelti žaidėjų meistri&scaron;kumą.<br />\r\nLAIKAS, VIETA, DALYVIAI<br />\r\nVaržybos vyks 2018 rugpjūčio 16-18 dienomis Klaipėdoje, adresu Taikos pr. 70;<br />\r\n&bull; rugpjūčio 16 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis vaikai:<br />\r\nmini jaunučiai (-tės) 2007 gim. ir jaunesni;<br />\r\njaunučiai (-tės) 2004 &ndash; 2006 gim.<br />\r\nStartinis mokestis 7 eur.<br />\r\n&bull; rugpjūčio 17 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis visi norintys vyrai ir moterys<br />\r\n(moterys ir vyrai žais atskirai);<br />\r\nStartinis mokestis 15 eur.<br />\r\n&bull; rugpjūčio 18 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis vyrai nuo 50 m. ir moterys nuo 40<br />\r\nm. (moterys ir vyrai žais atskirai);<br />\r\nStartinis mokestis 10 eur.</p>', 'Mergaitės 2007 ir jaunesnės', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2019-07-23 13:52:33', '2019-07-23 13:52:33', '2019-08-16'),
(13, 'Berniukai 2004-2006 - Klaipėda Open 2019', '<p>TURNYRO TIKSLAS<br />\r\n&bull; Populiarinti stalo teniso sporto &scaron;aką;<br />\r\n&bull; plėtoti draugi&scaron;kus ry&scaron;ius ne tik Lietuvoje, bet ir su užsienio sportininkais;<br />\r\n&bull; kelti žaidėjų meistri&scaron;kumą.<br />\r\nLAIKAS, VIETA, DALYVIAI<br />\r\nVaržybos vyks 2018 rugpjūčio 16-18 dienomis Klaipėdoje, adresu Taikos pr. 70;<br />\r\n&bull; rugpjūčio 16 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis vaikai:<br />\r\nmini jaunučiai (-tės) 2007 gim. ir jaunesni;<br />\r\njaunučiai (-tės) 2004 &ndash; 2006 gim.<br />\r\nStartinis mokestis 7 eur.<br />\r\n&bull; rugpjūčio 17 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis visi norintys vyrai ir moterys<br />\r\n(moterys ir vyrai žais atskirai);<br />\r\nStartinis mokestis 15 eur.<br />\r\n&bull; rugpjūčio 18 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis vyrai nuo 50 m. ir moterys nuo 40<br />\r\nm. (moterys ir vyrai žais atskirai);<br />\r\nStartinis mokestis 10 eur.</p>', 'Berniukai 2004-2006', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2019-07-23 13:53:10', '2019-07-23 13:53:10', '2019-08-16'),
(14, 'Berniukai 2007 ir jaunesni - Klaipėda Open 2019', '<p>TURNYRO TIKSLAS<br />\r\n&bull; Populiarinti stalo teniso sporto &scaron;aką;<br />\r\n&bull; plėtoti draugi&scaron;kus ry&scaron;ius ne tik Lietuvoje, bet ir su užsienio sportininkais;<br />\r\n&bull; kelti žaidėjų meistri&scaron;kumą.<br />\r\nLAIKAS, VIETA, DALYVIAI<br />\r\nVaržybos vyks 2018 rugpjūčio 16-18 dienomis Klaipėdoje, adresu Taikos pr. 70;<br />\r\n&bull; rugpjūčio 16 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis vaikai:<br />\r\nmini jaunučiai (-tės) 2007 gim. ir jaunesni;<br />\r\njaunučiai (-tės) 2004 &ndash; 2006 gim.<br />\r\nStartinis mokestis 7 eur.<br />\r\n&bull; rugpjūčio 17 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis visi norintys vyrai ir moterys<br />\r\n(moterys ir vyrai žais atskirai);<br />\r\nStartinis mokestis 15 eur.<br />\r\n&bull; rugpjūčio 18 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis vyrai nuo 50 m. ir moterys nuo 40<br />\r\nm. (moterys ir vyrai žais atskirai);<br />\r\nStartinis mokestis 10 eur.</p>', 'Berniukai 2007 ir jaunesni', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2019-07-23 13:53:59', '2019-07-23 13:53:59', '2019-08-16'),
(15, 'Vyrai \"Open\" grupė - Klaipėda Open 2019', '<p>TURNYRO TIKSLAS<br />\r\n&bull; Populiarinti stalo teniso sporto &scaron;aką;<br />\r\n&bull; plėtoti draugi&scaron;kus ry&scaron;ius ne tik Lietuvoje, bet ir su užsienio sportininkais;<br />\r\n&bull; kelti žaidėjų meistri&scaron;kumą.<br />\r\nLAIKAS, VIETA, DALYVIAI<br />\r\nVaržybos vyks 2018 rugpjūčio 16-18 dienomis Klaipėdoje, adresu Taikos pr. 70;<br />\r\n&bull; rugpjūčio 16 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis vaikai:<br />\r\nmini jaunučiai (-tės) 2007 gim. ir jaunesni;<br />\r\njaunučiai (-tės) 2004 &ndash; 2006 gim.<br />\r\nStartinis mokestis 7 eur.<br />\r\n&bull; rugpjūčio 17 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis visi norintys vyrai ir moterys<br />\r\n(moterys ir vyrai žais atskirai);<br />\r\nStartinis mokestis 15 eur.<br />\r\n&bull; rugpjūčio 18 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis vyrai nuo 50 m. ir moterys nuo 40<br />\r\nm. (moterys ir vyrai žais atskirai);<br />\r\nStartinis mokestis 10 eur.</p>', 'Vyrai \"Open\" grupė', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2019-07-23 13:54:51', '2019-07-23 13:54:51', '2019-08-16'),
(16, 'Moterys \"Open\" grupė - Klaipėda Open', '<p>TURNYRO TIKSLAS<br />\r\n&bull; Populiarinti stalo teniso sporto &scaron;aką;<br />\r\n&bull; plėtoti draugi&scaron;kus ry&scaron;ius ne tik Lietuvoje, bet ir su užsienio sportininkais;<br />\r\n&bull; kelti žaidėjų meistri&scaron;kumą.<br />\r\nLAIKAS, VIETA, DALYVIAI<br />\r\nVaržybos vyks 2018 rugpjūčio 16-18 dienomis Klaipėdoje, adresu Taikos pr. 70;<br />\r\n&bull; rugpjūčio 16 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis vaikai:<br />\r\nmini jaunučiai (-tės) 2007 gim. ir jaunesni;<br />\r\njaunučiai (-tės) 2004 &ndash; 2006 gim.<br />\r\nStartinis mokestis 7 eur.<br />\r\n&bull; rugpjūčio 17 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis visi norintys vyrai ir moterys<br />\r\n(moterys ir vyrai žais atskirai);<br />\r\nStartinis mokestis 15 eur.<br />\r\n&bull; rugpjūčio 18 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis vyrai nuo 50 m. ir moterys nuo 40<br />\r\nm. (moterys ir vyrai žais atskirai);<br />\r\nStartinis mokestis 10 eur.</p>', 'Moterys \"Open\" grupė', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2019-07-23 13:55:33', '2019-07-23 13:55:33', '2019-08-16'),
(17, 'Vyrai 50+ - Klaipėda Open 2019', '<p>TURNYRO TIKSLAS<br />\r\n&bull; Populiarinti stalo teniso sporto &scaron;aką;<br />\r\n&bull; plėtoti draugi&scaron;kus ry&scaron;ius ne tik Lietuvoje, bet ir su užsienio sportininkais;<br />\r\n&bull; kelti žaidėjų meistri&scaron;kumą.<br />\r\nLAIKAS, VIETA, DALYVIAI<br />\r\nVaržybos vyks 2018 rugpjūčio 16-18 dienomis Klaipėdoje, adresu Taikos pr. 70;<br />\r\n&bull; rugpjūčio 16 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis vaikai:<br />\r\nmini jaunučiai (-tės) 2007 gim. ir jaunesni;<br />\r\njaunučiai (-tės) 2004 &ndash; 2006 gim.<br />\r\nStartinis mokestis 7 eur.<br />\r\n&bull; rugpjūčio 17 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis visi norintys vyrai ir moterys<br />\r\n(moterys ir vyrai žais atskirai);<br />\r\nStartinis mokestis 15 eur.<br />\r\n&bull; rugpjūčio 18 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis vyrai nuo 50 m. ir moterys nuo 40<br />\r\nm. (moterys ir vyrai žais atskirai);<br />\r\nStartinis mokestis 10 eur.</p>', 'Vyrai 50+', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2019-07-23 13:56:44', '2019-07-23 13:56:44', '2019-08-16'),
(18, 'Moterys 40+ - Klaipėda Open 2019', '<p>TURNYRO TIKSLAS<br />\r\n&bull; Populiarinti stalo teniso sporto &scaron;aką;<br />\r\n&bull; plėtoti draugi&scaron;kus ry&scaron;ius ne tik Lietuvoje, bet ir su užsienio sportininkais;<br />\r\n&bull; kelti žaidėjų meistri&scaron;kumą.<br />\r\nLAIKAS, VIETA, DALYVIAI<br />\r\nVaržybos vyks 2018 rugpjūčio 16-18 dienomis Klaipėdoje, adresu Taikos pr. 70;<br />\r\n&bull; rugpjūčio 16 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis vaikai:<br />\r\nmini jaunučiai (-tės) 2007 gim. ir jaunesni;<br />\r\njaunučiai (-tės) 2004 &ndash; 2006 gim.<br />\r\nStartinis mokestis 7 eur.<br />\r\n&bull; rugpjūčio 17 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis visi norintys vyrai ir moterys<br />\r\n(moterys ir vyrai žais atskirai);<br />\r\nStartinis mokestis 15 eur.<br />\r\n&bull; rugpjūčio 18 d. 11.00 val., (atvykimas iki 10.30 val.) varžysis vyrai nuo 50 m. ir moterys nuo 40<br />\r\nm. (moterys ir vyrai žais atskirai);<br />\r\nStartinis mokestis 10 eur.</p>', 'Moterys 40+', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2019-07-23 13:57:23', '2019-07-23 13:57:23', '2019-08-16'),
(19, '2019 m. Žemaitijos regiono asmeninės stalo teniso pirmenybės - VYRŲ grupė', '<p><strong>Dalyviai.</strong><br />\r\nVaržybose leidžiama dalyvauti visiems Lietuvos Respublikos Žemaitijos regione esančių Klaipėdos,<br />\r\n&Scaron;iaulių, &Scaron;ilutės, Kelmės, Raseinių, Tel&scaron;ių, Mažeikių, Tauragės, Plungės, Kretingos, Palangos, &Scaron;ventosios,<br />\r\nJurbarko, Akmenės, Skuodo, &Scaron;ilalės, Rietavo, Žagarės miestų ir rajonų žaidėjams bei žaidėjams, gimusiems ir<br />\r\nužaugusiems &scaron;iuose miestuose ir atstovaujantiems gimtuosius klubus, nors &scaron;iuo metu gyvenantiems kituose<br />\r\nLietuvos regionuose arba užsienyje.</p>\r\n\r\n<p><br />\r\n<strong>Varžybos vyks &scaron;iose grupėse:</strong><br />\r\n&bull; VYRŲ gr. (amžius neribojimas), SENJORŲ vyrų gr. (50m+), MOTERŲ gr. (amžius<br />\r\nneribojimas).<br />\r\n&bull; Vyrai ir moterys žais atskirose grupėse, tačiau moterims bus suteikta galimybė pasirinkti žaisti vyrų arba<br />\r\nmoterų grupėje.<br />\r\nVaržybose dalyvauti GALI ir tie žaidėjai, kurie 2019 m. nedalyvavo Žemaitijos komandinėse<br />\r\npirmenybėse.<br />\r\nDalyviai neribojami pagal reitingą ar žaidimą LSTA lygose.<br />\r\nSportininkai už savo sveikatą visų varžybų metu atsako patys.</p>\r\n\r\n<p><br />\r\n<strong>Varžybų vieta ir laikas.</strong><br />\r\nPirmenybės vyks 2019 m. lapkričio 9 dieną Klaipėdoje, Taikos pr. 70 (Žvejų rūmuose), VSTA sporto<br />\r\nsalėje.<br />\r\nAtvykimas į varžybas iki 10.00 val., varžybų pradžia 11.00 val.<br />\r\nVisose grupėse bus skaičiuojamas reitingas.</p>', 'VYRŲ gr. (amžius neribojimas)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2019-10-19 07:38:55', '2019-10-19 07:38:55', '2019-11-09'),
(20, '2019 m. Žemaitijos regiono asmeninės stalo teniso pirmenybės - SENJORŲ Grupė', '<p><strong>Dalyviai.</strong><br />\r\nVaržybose leidžiama dalyvauti visiems Lietuvos Respublikos Žemaitijos regione esančių Klaipėdos,<br />\r\n&Scaron;iaulių, &Scaron;ilutės, Kelmės, Raseinių, Tel&scaron;ių, Mažeikių, Tauragės, Plungės, Kretingos, Palangos, &Scaron;ventosios,<br />\r\nJurbarko, Akmenės, Skuodo, &Scaron;ilalės, Rietavo, Žagarės miestų ir rajonų žaidėjams bei žaidėjams, gimusiems ir<br />\r\nužaugusiems &scaron;iuose miestuose ir atstovaujantiems gimtuosius klubus, nors &scaron;iuo metu gyvenantiems kituose<br />\r\nLietuvos regionuose arba užsienyje.</p>\r\n\r\n<p><br />\r\n<strong>Varžybos vyks &scaron;iose grupėse:</strong><br />\r\n&bull; VYRŲ gr. (amžius neribojimas), SENJORŲ vyrų gr. (50m+), MOTERŲ gr. (amžius<br />\r\nneribojimas).<br />\r\n&bull; Vyrai ir moterys žais atskirose grupėse, tačiau moterims bus suteikta galimybė pasirinkti žaisti vyrų arba<br />\r\nmoterų grupėje.<br />\r\nVaržybose dalyvauti GALI ir tie žaidėjai, kurie 2019 m. nedalyvavo Žemaitijos komandinėse<br />\r\npirmenybėse.<br />\r\nDalyviai neribojami pagal reitingą ar žaidimą LSTA lygose.<br />\r\nSportininkai už savo sveikatą visų varžybų metu atsako patys.</p>\r\n\r\n<p><br />\r\n<strong>Varžybų vieta ir laikas.</strong><br />\r\nPirmenybės vyks 2019 m. lapkričio 9 dieną Klaipėdoje, Taikos pr. 70 (Žvejų rūmuose), VSTA sporto<br />\r\nsalėje.<br />\r\nAtvykimas į varžybas iki 10.00 val., varžybų pradžia 11.00 val.<br />\r\nVisose grupėse bus skaičiuojamas reitingas.</p>', 'SENJORŲ vyrų gr. (50m+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2019-10-19 09:08:44', '2019-10-19 09:08:44', '2019-11-09'),
(21, '2019 m. Žemaitijos regiono asmeninės stalo teniso pirmenybės - MOTERŲ Grupė', '<p><strong>Dalyviai.</strong><br />\r\nVaržybose leidžiama dalyvauti visiems Lietuvos Respublikos Žemaitijos regione esančių Klaipėdos,<br />\r\n&Scaron;iaulių, &Scaron;ilutės, Kelmės, Raseinių, Tel&scaron;ių, Mažeikių, Tauragės, Plungės, Kretingos, Palangos, &Scaron;ventosios,<br />\r\nJurbarko, Akmenės, Skuodo, &Scaron;ilalės, Rietavo, Žagarės miestų ir rajonų žaidėjams bei žaidėjams, gimusiems ir<br />\r\nužaugusiems &scaron;iuose miestuose ir atstovaujantiems gimtuosius klubus, nors &scaron;iuo metu gyvenantiems kituose<br />\r\nLietuvos regionuose arba užsienyje.</p>\r\n\r\n<p><br />\r\n<strong>Varžybos vyks &scaron;iose grupėse:</strong><br />\r\n&bull; VYRŲ gr. (amžius neribojimas), SENJORŲ vyrų gr. (50m+), MOTERŲ gr. (amžius<br />\r\nneribojimas).<br />\r\n&bull; Vyrai ir moterys žais atskirose grupėse, tačiau moterims bus suteikta galimybė pasirinkti žaisti vyrų arba<br />\r\nmoterų grupėje.<br />\r\nVaržybose dalyvauti GALI ir tie žaidėjai, kurie 2019 m. nedalyvavo Žemaitijos komandinėse<br />\r\npirmenybėse.<br />\r\nDalyviai neribojami pagal reitingą ar žaidimą LSTA lygose.<br />\r\nSportininkai už savo sveikatą visų varžybų metu atsako patys.</p>\r\n\r\n<p><br />\r\n<strong>Varžybų vieta ir laikas.</strong><br />\r\nPirmenybės vyks 2019 m. lapkričio 9 dieną Klaipėdoje, Taikos pr. 70 (Žvejų rūmuose), VSTA sporto<br />\r\nsalėje.<br />\r\nAtvykimas į varžybas iki 10.00 val., varžybų pradžia 11.00 val.<br />\r\nVisose grupėse bus skaičiuojamas reitingas.</p>', 'MOTERŲ gr. (amžius neribojimas)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2019-10-19 09:09:33', '2019-10-19 09:09:33', '2019-11-09'),
(22, 'Žemaitijos regiono asmeninės vaikų pirmenybės - Mergaitės 2005-2009 m.', '<p><strong>VYKDYMO SISTEMA</strong></p>\r\n\r\n<p>&Scaron;ios varžybos bus vykdomos etapais &ndash; turais. I&scaron; viso vyks 4 turai. Kiekvieno turo metu dalyviai už užimtas vietas gaus ta&scaron;kus. Kiekvieno turo metu varžybų prizininkai bus apdovanoti. Po paskutinio turo bus sumuojami rezultatai ir vertinami kiekvieno žaidėjo 3-jų geriausių turų rezultatai. Geriausi visų turų žaidėjai bus apdovanoti paskutinio turo metu.<br />\r\nKiekviename etape varžybų dalyviai žais dviejų minusų sistema su visų vietų i&scaron;ai&scaron;kinimu. Varžybų sistema gali keistis, priklausomai nuo dalyvių skaičiaus.<br />\r\nPo kiekvieno turo, rezultatai skelbiami internetiniame puslapyje <a href=\"http://www.riesestenisas.lt/\">www.vsta.lt</a>, <em>Facebook paskyroje</em> &ldquo;Vakarų stalo teniso akademija&rdquo;</p>', 'Mergaitės 2005-2009 m.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2019-11-20 18:28:48', '2019-11-20 18:28:48', '2019-12-14'),
(23, 'Žemaitijos regiono asmeninės vaikų pirmenybės - Berniukai 2005 – 2009 m. gim.', '<p><strong>VYKDYMO SISTEMA</strong></p>\r\n\r\n<p>&Scaron;ios varžybos bus vykdomos etapais &ndash; turais. I&scaron; viso vyks 4 turai. Kiekvieno turo metu dalyviai už užimtas vietas gaus ta&scaron;kus. Kiekvieno turo metu varžybų prizininkai bus apdovanoti. Po paskutinio turo bus sumuojami rezultatai ir vertinami kiekvieno žaidėjo 3-jų geriausių turų rezultatai. Geriausi visų turų žaidėjai bus apdovanoti paskutinio turo metu.<br />\r\nKiekviename etape varžybų dalyviai žais dviejų minusų sistema su visų vietų i&scaron;ai&scaron;kinimu. Varžybų sistema gali keistis, priklausomai nuo dalyvių skaičiaus.<br />\r\nPo kiekvieno turo, rezultatai skelbiami internetiniame puslapyje <a href=\"http://www.riesestenisas.lt/\">www.vsta.lt</a>, <em>Facebook paskyroje</em> &ldquo;Vakarų stalo teniso akademija&rdquo;</p>', 'Berniukai 2005 – 2009 m. gim.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2019-11-20 18:30:17', '2019-11-20 18:30:17', '2019-12-14'),
(24, 'Žemaitijos regiono asmeninės vaikų pirmenybės - Berniukai  2009 m. gim. ir jaunesni', '<p><strong>VYKDYMO SISTEMA</strong></p>\r\n\r\n<p>&Scaron;ios varžybos bus vykdomos etapais &ndash; turais. I&scaron; viso vyks 4 turai. Kiekvieno turo metu dalyviai už užimtas vietas gaus ta&scaron;kus. Kiekvieno turo metu varžybų prizininkai bus apdovanoti. Po paskutinio turo bus sumuojami rezultatai ir vertinami kiekvieno žaidėjo 3-jų geriausių turų rezultatai. Geriausi visų turų žaidėjai bus apdovanoti paskutinio turo metu.<br />\r\nKiekviename etape varžybų dalyviai žais dviejų minusų sistema su visų vietų i&scaron;ai&scaron;kinimu. Varžybų sistema gali keistis, priklausomai nuo dalyvių skaičiaus.<br />\r\nPo kiekvieno turo, rezultatai skelbiami internetiniame puslapyje <a href=\"http://www.riesestenisas.lt/\">www.vsta.lt</a>, <em>Facebook paskyroje</em> &ldquo;Vakarų stalo teniso akademija&rdquo;</p>', 'Berniukai  2009 m. gim. ir jaunesni', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2019-11-20 18:31:19', '2019-11-20 18:31:19', '2019-12-14'),
(25, 'Žemaitijos regiono asmeninės vaikų pirmenybės - Mergaitės 2009 m. gim. ir jaunesnės', '<p><strong>VYKDYMO SISTEMA</strong></p>\r\n\r\n<p>&Scaron;ios varžybos bus vykdomos etapais &ndash; turais. I&scaron; viso vyks 4 turai. Kiekvieno turo metu dalyviai už užimtas vietas gaus ta&scaron;kus. Kiekvieno turo metu varžybų prizininkai bus apdovanoti. Po paskutinio turo bus sumuojami rezultatai ir vertinami kiekvieno žaidėjo 3-jų geriausių turų rezultatai. Geriausi visų turų žaidėjai bus apdovanoti paskutinio turo metu.<br />\r\nKiekviename etape varžybų dalyviai žais dviejų minusų sistema su visų vietų i&scaron;ai&scaron;kinimu. Varžybų sistema gali keistis, priklausomai nuo dalyvių skaičiaus.<br />\r\nPo kiekvieno turo, rezultatai skelbiami internetiniame puslapyje <a href=\"http://www.riesestenisas.lt/\">www.vsta.lt</a>, <em>Facebook paskyroje</em> &ldquo;Vakarų stalo teniso akademija&rdquo;</p>', 'Mergaitės 2009 m. gim. ir jaunesnės', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2019-11-20 18:32:40', '2019-11-20 18:32:40', '2019-12-14');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `events`
--
ALTER TABLE `events`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `events`
--
ALTER TABLE `events`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=26;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
